wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1733314806
    t:
      1:
      - 1
      - 37
      - 41
      - 49
      - 50
      - 55
      - 63
      - 74
      - 80
      - 82
      - 106
      2:
      - 1
      - 37
      - 41
      - 49
      - 50
      - 55
      - 63
      - 74
      - 80
      - 82
      - 106
      3:
      - 13
      - 23
      - 24
      4: 3.10.14
      5: 0.17.8
      8:
      - 2
      - 5
      13: linux-x86_64
