_wandb:
    value:
        cli_version: 0.17.8
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 37
                - 41
                - 49
                - 50
                - 55
                - 63
                - 74
                - 80
                - 82
                - 106
            "2":
                - 1
                - 37
                - 41
                - 49
                - 50
                - 55
                - 63
                - 74
                - 80
                - 82
                - 106
            "3":
                - 13
                - 23
                - 24
                - 55
            "4": 3.10.14
            "5": 0.17.8
            "8":
                - 2
                - 5
            "12": 0.17.8
            "13": linux-x86_64
