_target_: src.models.lidc_segcls.segcls_module.LIDCSegClsModule

use_ema: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 15

net:
  _target_: src.models.lidc_segcls.net.LIDCSegClsNet
  seg_net:
    _target_: src.models.lidc_segcls.net.CaraNet
    channel: 32

  cls_net:
    _target_: src.models.lidc_segcls.net.resnet_cls.ResNet1D
    input_size: 32
    hidden_size_list: [16, 8]
    n_classes: ${model.n_classes}

  matching_threshold: 0.5

groups: 
  - cancer
  - malignancy


weights_classes: 
  - null
  - null

n_classes: [4, 7]
image_size: ${data.image_size}
size_rates: [0.75, 1, 1.25]